@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
        stage('Download')
        {
            steps
            {
                script
                {
                     cicd.gitDownload('mavenpractice')
                }
            }
        }
        stage('build')
        {
            steps
            {
                script
                {
                    cicd.buildArtefact()
                }
            }
        }
        stage('Deployment')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("Declarativepipeline5","172.31.94.12","mytest")
                }
            }
        }
        stage('Testing')
        {
            steps
            {
                script
                {
                    cicd.gitDownload('FunctionalTesting')
                    cicd.seleniumtesting('Declarativepipeline5')
                }
            }
        }
        stage('Delivery')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("Declarativepipeline5","172.31.90.210","prodserver")
                }
            }
        }
    }
}
